language: python
sudo: enabled
python:
    - 2.7
    - 3.6
before-install:
    - sudo apt-get install -y libhdf5-dev
install: 
    - pip install cython
    - pip install -r requirements.txt
    - pip install pytest
    - pip install flaky
    - pip install .
script: python setup.py test
